# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ns3socket', ['core'])
    module.source = [
        'model/ns3socket.cc',
        'helper/ns3socket-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ns3socket')
    module_test.source = [
        'test/ns3socket-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/ns3socket-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'ns3socket'
    headers.source = [
        'model/ns3socket.h',
        'helper/ns3socket-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

