# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ns3socket-example', ['ns3socket'])
    obj.source = 'ns3socket-example.cc'

